// ==========================================
// 50 CÂU HỎI TRẮC NGHIỆM CHO MỖI NGÔN NGỮ
// ==========================================
const quizDB = {
    javascript: [
        { q: "Câu lệnh nào dùng để in dữ liệu ra console?", a: ["console.log()", "print()", "cout", "System.out.println()"], c: 0 },
        { q: "Khai báo biến trong JS, cái nào được dùng nhiều nhất hiện đại?", a: ["var age = 25", "let age = 25", "const age = 25", "cả B và C đều đúng"], c: 3 },
        { q: "Kết quả của 10 + '5' trong JavaScript là gì?", a: ["15", "105", "Lỗi", "undefined"], c: 1 },
        { q: "Hàm nào được dùng để kiểm tra độ dài chuỗi?", a: ["length()", ".length", ".size()", ".count()"], c: 1 },
        { q: "Cú pháp vòng lặp for đúng là?", a: ["for(let i=0 i<5 i++)", "for(let i=0; i<5; i++)", "for i in range(5)", "while(i<5)"], c: 1 },
        { q: "Array trong JS được khai báo như thế nào?", a: ["let arr = (1,2,3)", "let arr = [1,2,3]", "let arr = {1,2,3}", "let arr = 1,2,3"], c: 1 },
        { q: "Hàm trong JS bắt đầu bằng từ khóa nào?", a: ["func", "function", "def", "method"], c: 1 },
        { q: "1 === '1' sẽ trả về gì?", a: ["true", "false", "1", "undefined"], c: 1 },
        { q: "Để nối chuỗi, ta dùng ký tự nào?", a: ["-", "*", "+", "&"], c: 2 },
        { q: "undefined có phải là kiểu dữ liệu trong JS không?", a: ["Không", "Có", "Có nhưng hiếm", "Tùy trường hợp"], c: 1 },
        { q: "Phương thức nào dùng để loại bỏ khoảng trắng ở hai đầu chuỗi?", a: ["slice()", "trim()", "cut()", "remove()"], c: 1 },
        { q: "Hàm push() làm gì với array?", a: ["Xóa phần tử", "Thêm phần tử vào cuối", "Xóa phần tử đầu", "Đảo ngược array"], c: 1 },
        { q: "typeof [] sẽ trả về gì?", a: ["array", "object", "list", "undefined"], c: 1 },
        { q: "Điều nào sai về JSON?", a: ["JSON là format text", "JSON dùng {} cho object", "JSON dùng [] cho array", "JSON chấp nhận hàm trong giá trị"], c: 3 },
        { q: "Template literals trong JS dùng ký tự nào?", a: ["''", '\"\"', "``", "''"], c: 2 },
        { q: "Hàm filter() trả về gì?", a: ["Một giá trị đơn", "Một mảng mới", "true/false", "Lỗi"], c: 1 },
        { q: "const có thể được gán lại giá trị không?", a: ["Có", "Không", "Tùy trường hợp", "Chỉ lần đầu"], c: 1 },
        { q: "Phương thức nào tạo ra một mảng mới từ mảng cũ?", a: ["copy()", "clone()", "map()", "duplicate()"], c: 2 },
        { q: "setTimeout() dùng để làm gì?", a: ["Nạp lại trang", "Chạy code sau khoảng thời gian", "Tạo vòng lặp", "Kiểm tra thời gian"], c: 1 },
        { q: "Ternary operator trong JS là?", a: ["if-else", "? :", "switch", "||"], c: 1 },
        { q: "Phương thức nào chuyển chuỗi thành số?", a: ["toString()", "parseInt()", "toNumber()", "convert()"], c: 1 },
        { q: "Object.keys() trả về gì?", a: ["Mảng các giá trị", "Mảng các khóa", "Object mới", "String"], c: 1 },
        { q: "Spread operator trong JS là gì?", a: ["...", "**", "<<", ">>"], c: 0 },
        { q: "Hàm find() trả về cái gì?", a: ["Mảng các phần tử", "Phần tử đầu tiên khớp", "Số lượng", "true/false"], c: 1 },
        { q: "split() dùng để làm gì?", a: ["Nối chuỗi", "Tách chuỗi thành mảng", "Kiểm tra chuỗi", "Xóa chuỗi"], c: 1 },
        { q: "Closure trong JS là gì?", a: ["Vòng lặp", "Hàm lồng nhau có thể truy cập biến ngoài", "Điều kiện", "Biến toàn cục"], c: 1 },
        { q: "Promise dùng để xử lý gì?", a: ["Bộ nhớ", "Lập trình bất đồng bộ", "Mảng", "Kiểu dữ liệu"], c: 1 },
        { q: "async/await là gì?", a: ["Vòng lặp", "Cách viết Promise dễ hơn", "Hàm tính toán", "Biến"], c: 1 },
        { q: "NaN là cách viết tắt của gì?", a: ["Not a Null", "Not a Number", "Null And Nothing", "No Array Numbers"], c: 1 },
        { q: "Phương thức includes() kiểm tra gì?", a: ["Độ dài", "Sự tồn tại của phần tử", "Kiểu dữ liệu", "Biến toàn cục"], c: 1 },
        { q: "Arrow function được viết như thế nào?", a: ["=> () {}", "() => {}", "function () => {}", "=> function {}"], c: 1 },
        { q: "Hàm reverse() làm gì?", a: ["Tạo mảng mới", "Đảo ngược mảng", "Sắp xếp mảng", "Xóa mảy"], c: 1 },
        { q: "localStorage dùng để làm gì?", a: ["Tạo biến toàn cục", "Lưu dữ liệu trên trình duyệt", "Tạo hàm", "Nạp lại trang"], c: 1 },
        { q: "Phương thức join() chuyển gì thành gì?", a: ["Mảng thành chuỗi", "Chuỗi thành object", "Object thành mảy", "Số thành chuỗi"], c: 0 },
        { q: "this trong JS tham chiếu đến gì?", a: ["Hàm", "Đối tượng chủ sở hữu phương thức", "Biến", "undefined"], c: 1 },
        { q: "Hàm reduce() dùng để làm gì?", a: ["Lọc mảy", "Tính tổng/gộp thành 1 giá trị", "Tìm phần tử", "Sắp xếp"], c: 1 },
        { q: "Object.assign() dùng để làm gì?", a: ["So sánh object", "Sao chép/gộp object", "Xóa object", "Kiểm tra object"], c: 1 },
        { q: "Hàm setTimeout() với delay 0 làm gì?", a: ["Chạy ngay lập tức", "Đẩy vào cuối call stack", "Chạy lại", "Hủy bỏ"], c: 1 },
        { q: "Destructuring là gì?", a: ["Hủy biến", "Trích xuất giá trị từ array/object", "Xóa dữ liệu", "Tạo biến"], c: 1 },
        { q: "hoisting trong JavaScript là gì?", a: ["Đặt hàm trên cùng", "Khóa biến/hàm lên đầu phạm vi", "Xóa biến", "Tạo scope mới"], c: 1 },
        { q: "null === undefined sẽ trả về gì?", a: ["true", "false", "null", "undefined"], c: 1 },
        { q: "Phương thức concat() làm gì?", a: ["Nối mảy", "Cắt mảy", "Đảo mảy", "Lọc mảy"], c: 0 },
        { q: "try-catch dùng để xử lý gì?", a: ["Vòng lặp", "Lỗi", "Điều kiện", "Hàm"], c: 1 },
        { q: "Hàm every() kiểm tra gì?", a: ["Có phần tử nào được chạy", "Tất cả phần tử có thỏa điều kiện", "Phần tử đầu", "Độ dài mảy"], c: 1 },
        { q: "some() khác every() như thế nào?", a: ["same", "some kiểm tra ít nhất 1, every kiểm tra tất cả", "some khác all", "some không dùng được"], c: 1 },
        { q: "bind() dùng để làm gì?", a: ["Nối chuỗi", "Tạo hàm mới với this cố định", "Xóa hàm", "Gọi hàm"], c: 1 },
        { q: "Phương thức charAt() trả về gì?", a: ["Đoạn chuỗi", "Ký tự tại vị trí", "Mảy ký tự", "Độ dài"], c: 1 },
        { q: "isNaN() kiểm tra gì?", a: ["Là number", "Không phải number", "Là string", "Là boolean"], c: 1 },
        { q: "Hàm getters/setters trong class dùng để?", a: ["Tạo method", "Kiểm soát truy cập thuộc tính", "Tạo biến", "Xóa thuộc tính"], c: 1 }
    ],
    python: [
        { q: "Hàm nào dùng để in dữ liệu ra?", a: ["cout", "print()", "System.out.println()", "puts"], c: 1 },
        { q: "Cú pháp khai báo biến nào đúng?", a: ["int age = 25", "age: int = 25", "age = 25", "var age = 25"], c: 2 },
        { q: "Cách tạo list trong Python?", a: ["list = (1,2,3)", "list = {1,2,3}", "list = [1,2,3]", "list = 1,2,3"], c: 2 },
        { q: "Hàm lặp for trong Python dùng từ khóa nào?", a: ["for", "while", "loop", "repeat"], c: 0 },
        { q: "range(5) sẽ sinh ra dãy số nào?", a: ["1,2,3,4,5", "0,1,2,3,4", "1,2,3,4", "0,1,2,3,4,5"], c: 1 },
        { q: "Cách lấy độ dài list là?", a: [".length()", "len(list)", ".size()", ".count()"], c: 1 },
        { q: "Comment trong Python dùng ký tự nào?", a: ["//", "/**/", "#", "--"], c: 2 },
        { q: "Dictionary trong Python khai báo như thế nào?", a: ["dict = (key: value)", "dict = {key: value}", "dict = [key, value]", "dict = key, value"], c: 1 },
        { q: "Hàm dùng để kiểm tra kiểu dữ liệu?", a: ["typeof", "isinstance()", "getType()", "checkType()"], c: 1 },
        { q: "Để tạo hàm, từ khóa nào được dùng?", a: ["function", "fun", "def", "method"], c: 2 },
        { q: "String trong Python có thể được tạo bằng?", a: ["Chỉ dấu ngoặc đơn", "Chỉ dấu ngoặc kép", "Cả hai hoặc ba dấu ngoặc", "Chỉ backtick"], c: 2 },
        { q: "Phương thức split() trên string làm gì?", a: ["Nối string", "Tách string thành list", "Xóa string", "Kiểm tra string"], c: 1 },
        { q: "Slicing string trong Python là gì?", a: ["Cắt một phần string", "Nối string", "Xóa string", "Sao chép string"], c: 0 },
        { q: "Hàm map() dùng để làm gì?", a: ["Lọc dữ liệu", "Áp dụng hàm cho mỗi phần tử", "Tìm phần tử", "Sắp xếp danh sách"], c: 1 },
        { q: "Hàm filter() trả về gì?", a: ["Một phần tử", "Danh sách mới các phần tử thỏa điều kiện", "True/False", "Lỗi"], c: 1 },
        { q: "List comprehension trong Python là gì?", a: ["Cách tạo loop", "Cách tạo list ngắn gọn", "Cách tạo dict", "Cách tạo set"], c: 1 },
        { q: "Tuple khác List như thế nào?", a: ["Cả hai giống nhau", "Tuple không thể thay đổi", "List nhanh hơn", "Tuple lớn hơn"], c: 1 },
        { q: "set() trong Python dùng để làm gì?", a: ["Tạo list", "Tạo tập hợp không trùng lặp", "Tạo dict", "Tạo string"], c: 1 },
        { q: "Hàm enumerate() dùng để?", a: ["Đếm phần tử", "Lấy chỉ số và giá trị của mỗi phần tử", "Xóa phần tử", "Nối list"], c: 1 },
        { q: "Lambda function dùng để làm gì?", a: ["Tạo hàm tên", "Tạo hàm không tên ngắn gọn", "Tạo class", "Tạo biến"], c: 1 },
        { q: "Hàm zip() dùng để?", a: ["Nén file", "Gộp nhiều list thành một", "Xóa phần tử", "Tìm phần tử"], c: 1 },
        { q: "try-except dùng để xử lý gì?", a: ["Vòng lặp", "Lỗi", "Điều kiện", "Hàm"], c: 1 },
        { q: "else trong vòng for/while dùng để?", a: ["Chạy khi vòng lặp kết thúc bình thường", "Chạy khi điều kiện sai", "Không bao giờ chạy", "Chạy ngoài vòng"], c: 0 },
        { q: "Hàm isinstance() kiểm tra gì?", a: ["Sự tồn tại", "Kiểu dữ liệu", "Giá trị", "Tên biến"], c: 1 },
        { q: "Hàm sorted() có thay đổi list gốc không?", a: ["Có", "Không, trả về list mới", "Tùy trường hợp", "Chưa biết"], c: 1 },
        { q: "Decorator trong Python là gì?", a: ["Sửa đổi hàm mà không sửa code", "Tạo class", "Tạo module", "Xóa hàm"], c: 0 },
        { q: "Class trong Python tạo như thế nào?", a: ["class Ten:", "class Ten {}", "create Ten", "def Ten"], c: 0 },
        { q: "__init__() làm gì trong class?", a: ["Xóa object", "Constructor - khởi tạo object", "Kết thúc class", "staticmethod"], c: 1 },
        { q: "self trong method là gì?", a: ["Một từ khóa", "Tham chiếu đến object hiện tại", "Một hằng số", "Một hàm"], c: 1 },
        { q: "Hàm getattr() dùng để làm gì?", a: ["Xóa thuộc tính", "Lấy giá trị của thuộc tính", "Tạo thuộc tính", "So sánh thuộc tính"], c: 1 },
        { q: "Global keyword dùng để?", a: ["Tạo biến", "Sử dụng biến toàn cục trong hàm", "Tạo scope", "Xóa biến"], c: 1 },
        { q: "with statement dùng để?", a: ["Tạo vòng lặp", "Quản lý tài nguyên tự động", "Tạo điều kiện", "Tạo hàm"], c: 1 },
        { q: "Hàm abs() trả về gì?", a: ["Giá trị tuyệt đối", "Số lần xuất hiện", "Kiểu dữ liệu", "Độ dài"], c: 0 },
        { q: "round() dùng để làm gì?", a: ["Làm tròn số", "Loại bỏ số", "Tăng số", "Giảm số"], c: 0 },
        { q: "Hàm any() kiểm tra gì?", a: ["Tất cả true", "Ít nhất 1 true", "Tất cả false", "Không có gì"], c: 1 },
        { q: "Hàm all() kiểm tra gì?", a: ["Ít nhất 1 true", "Tất cả true", "Tất cả false", "Không có gì"], c: 1 },
        { q: "Hàm reversed() làm gì?", a: ["Xóa phần tử", "Đảo ngược thứ tự", "Sắp xếp", "Tìm kiếm"], c: 1 },
        { q: "Hàm sum() tính gì?", a: ["Số phần tử", "Tổng các phần tử", "Trung bình", "Lớn nhất"], c: 1 },
        { q: "max() và min() dùng để?", a: ["Tạo list", "Tìm giá trị lớn nhất và nhỏ nhất", "Sắp xếp list", "Xóa phần tử"], c: 1 },
        { q: "Phương thức startswith() kiểm tra gì?", a: ["Độ dài", "String bắt đầu bằng cái gì", "String kết thúc bằng gì", "Ký tự đặc biệt"], c: 1 },
        { q: "Phương thức replace() dùng để?", a: ["Tìm kiếm", "Thay thế chuỗi con", "Xóa chuỗi", "Nối chuỗi"], c: 1 },
        { q: "Hàm format() trên string dùng để?", a: ["Xóa format", "Định dạng string với giá trị", "Kiểm tra format", "Tạo format"], c: 1 },
        { q: "Hàm dir() hiển thị gì?", a: ["Đường dẫn", "Danh sách attributes của object", "Nội dung file", "Thư mục"], c: 1 },
        { q: "import * dùng để?", a: ["Import tất cả từ module", "Import một hàm", "Xóa import", "Không hợp lệ"], c: 0 },
        { q: "Hàm eval() làm gì?", a: ["Đánh giá biểu thức string thành code", "Xóa biến", "Tạo scope", "Kiểm tra lỗi"], c: 0 },
        { q: "Hàm exec() khác eval() như thế nào?", a: ["Cùng nhau", "exec không trả về giá trị", "eval an toàn hơn", "Không khác"], c: 1 }
    ],
    cpp: [
        { q: "Câu lệnh nào dùng để in dữ liệu ra?", a: ["cout", "print()", "printf()", "System.out"], c: 0 },
        { q: "Để sử dụng cout, phải include gì?", a: ["#include <stdio.h>", "#include <iostream>", "#include <cstdlib>", "#include <vector>"], c: 1 },
        { q: "Khai báo biến trong C++?", a: ["int age = 25;", "int age: 25;", "var age = 25;", "age: int = 25"], c: 0 },
        { q: "Array trong C++ được khai báo?", a: ["int arr = [1,2,3]", "int arr[3] = {1,2,3}", "array arr = {1,2,3}", "let arr = [1,2,3]"], c: 1 },
        { q: "Cú pháp vòng lặp for đúng là?", a: ["for i in range(10)", "for(int i=0; i<10; i++)", "for(i<10)", "repeat(10) {"], c: 1 },
        { q: "Để tạo hàm, cú pháp là?", a: ["func name() {}", "def name():", "type name() {}", "method name() {}"], c: 2 },
        { q: "String trong C++ phải include gì?", a: ["#include <string>", "#include <cstring>", "#include <stdio.h>", "Không cần"], c: 0 },
        { q: "Struct dùng để làm gì?", a: ["Khai báo hàm", "Nhóm dữ liệu", "Tạo loop", "Khai báo mảng"], c: 1 },
        { q: "Vector trong C++ là gì?", a: ["Biến thường", "Mảng động", "Hàm", "Kiểu bool"], c: 1 },
        { q: "nullptr dùng trong C++ như thế nào?", a: ["Giá trị 0", "Con trỏ rỗng", "Từ khóa", "Lỗi cú pháp"], c: 1 },
        { q: "Con trỏ (*) trong C++ là gì?", a: ["Toán tử nhân", "Lưu trữ địa chỉ bộ nhớ", "Xóa biến", "Tạo mảng"], c: 1 },
        { q: "Tham chiếu (&) trong C++ dùng để?", a: ["Địa chỉ", "Alias cho biến", "Xóa con trỏ", "Tạo hằng số"], c: 1 },
        { q: "new dùng để làm gì?", a: ["Tạo biến", "Cấp phát bộ nhớ động", "Xóa biến", "Nhập dữ liệu"], c: 1 },
        { q: "delete dùng để làm gì?", a: ["Xóa file", "Giải phóng bộ nhớ", "Xóa biến", "Reset biến"], c: 1 },
        { q: "Class trong C++ là gì?", a: ["Một hàm", "Một định nghĩa kiểu dữ liệu với methods", "Một mảng", "Một scope"], c: 1 },
        { q: "private trong class C++ có nghĩa là?", a: ["Công khai", "Chỉ dùng trong class", "Không thể truy cập", "Có access bởi subclass"], c: 1 },
        { q: "public trong class C++ có nghĩa là?", a: ["Kiểu dữ liệu", "Có thể truy cập từ bất kỳ đâu", "Chỉ định file", "Chỉ định lớp"], c: 1 },
        { q: "Constructor trong C++ dùng để?", a: ["Xóa object", "Khởi tạo object", "Tạo hàm", "Kết thúc chương trình"], c: 1 },
        { q: "Destructor trong C++ dùng để?", a: ["Tạo object", "Dọn dẹp object khi không dùng", "Tạo hàm mới", "Copy object"], c: 1 },
        { q: "const trong C++ là gì?", a: ["Biến có thể thay đổi", "Hằng số không thể thay đổi", "Biến từ khóa", "Một loại con trỏ"], c: 1 },
        { q: "static member trong class là gì?", a: ["Thành viên của instance", "Thành viên chung cho tất cả objects", "Biến cục bộ", "Hằng số"], c: 1 },
        { q: "inline function dùng để?", a: ["Nhập dữ liệu", "Tối ưu hóa bằng cách copy code", "Tạo scope", "Xóa hàm"], c: 1 },
        { q: "Operator overloading dùng để?", a: ["Xóa operator", "Định nghĩa lại operator cho class", "Tạo operator mới", "Kiểm tra operator"], c: 1 },
        { q: "Template trong C++ dùng để?", a: ["Tạo HTML", "Tạo function/class cho nhiều kiểu", "Tạo file", "Tạo scope"], c: 1 },
        { q: "STL (Standard Template Library) là gì?", a: ["Thư viện tiêu chuẩn của C++", "Một ngôn ngữ", "Một công cụ", "Một IDE"], c: 0 },
        { q: "Hàm sizeof() trả về gì?", a: ["Kích thước file", "Kích thước (bytes) của kiểu/biến", "Số phần tử", "Địa chỉ"], c: 1 },
        { q: "Hàm strcpy() dùng để?", a: ["So sánh string", "Sao chép string", "Tìm string", "Xóa string"], c: 1 },
        { q: "Hàm strlen() trả về gì?", a: ["String mới", "Độ dài string", "String con", "Ký tự"], c: 1 },
        { q: "Hàm strcmp() dùng để?", a: ["Sao chép string", "So sánh string", "Tìm string", "Xóa string"], c: 1 },
        { q: "Hàm strcat() dùng để?", a: ["Cắt string", "Nối string", "Tìm string", "So sánh string"], c: 1 },
        { q: "Hàm toupper() dùng để?", a: ["Chuyển thành chữ thường", "Chuyển thành chữ hoa", "Kiểm tra chữ", "Xóa chữ"], c: 1 },
        { q: "Hàm isdigit() kiểm tra gì?", a: ["Là chữ cái", "Là chữ số", "Là ký tự đặc biệt", "Là không gian"], c: 1 },
        { q: "Hàm isalpha() kiểm tra gì?", a: ["Là chữ số", "Là chữ cái", "Là ký tự đặc biệt", "Là khoảng trắng"], c: 1 },
        { q: "Hàm abs() trả về gì?", a: ["Giá trị tuyệt đối", "Giá trị âm", "Giá trị mặc định", "Giá trị max"], c: 0 },
        { q: "Hàm pow() tính gì?", a: ["Căn bậc hai", "Lũy thừa", "Logarit", "Giá trị tuyệt đối"], c: 1 },
        { q: "Hàm sqrt() dùng để?", a: ["Bình phương", "Căn bậc hai", "Lũy thừa", "Phép chia"], c: 1 },
        { q: "Hàm sin(), cos() tính gì?", a: ["Hàm riêng", "Hàm lượng giác", "Hàm logarit", "Hàm mũ"], c: 1 },
        { q: "Hàm rand() trả về gì?", a: ["Số nguyên tố", "Số ngẫu nhiên", "Số âm", "Số float"], c: 1 },
        { q: "Hàm atoi() dùng để?", a: ["Float sang int", "String sang int", "Int sang string", "Kiểm tra int"], c: 1 },
        { q: "Hàm itoa() dùng để?", a: ["Int sang string", "String sang int", "Int sang float", "Kiểm tra string"], c: 0 },
        { q: "Hàm memset() dùng để?", a: ["Tạo memory", "Set giá trị cho vùng memory", "Xóa memory", "Check memory"], c: 1 },
        { q: "Hàm memcpy() dùng để?", a: ["Tạo bản sao", "Copy dữ liệu từ vùng này sang vùng khác", "Xóa dữ liệu", "So sánh dữ liệu"], c: 1 },
        { q: "Hàm exit() dùng để?", a: ["Tạo folder", "Kết thúc chương trình", "Tạo file", "Xóa file"], c: 1 }
    ],
    java: [
        { q: "Câu lệnh in dữ liệu trong Java?", a: ["print()", "cout", "System.out.println()", "printf()"], c: 2 },
        { q: "Khai báo biến đúng trong Java?", a: ["int age = 25", "age: int = 25", "var age = 25", "age = int 25"], c: 0 },
        { q: "Array trong Java?", a: ["int[] arr = [1,2,3]", "int arr[] = {1,2,3}", "array arr = {1,2,3}", "List arr = {1,2,3}"], c: 1 },
        { q: "Vòng lặp for trong Java?", a: ["for i in range(10)", "for(int i=0; i<10; i++)", "for(i<10)", "repeat(10) {"], c: 1 },
        { q: "Class trong Java bắt đầu bằng?", a: ["class Main {", "Class Main {", "public class Main {", "Cả A và C đúng"], c: 3 },
        { q: "Method main trong Java?", a: ["public static void main()", "public void main(String[])", "public static void main(String[])", "static main()"], c: 2 },
        { q: "ArrayList là gì?", a: ["Mảng thường", "Mảng động", "List tĩnh", "Hàm trong java.util"], c: 1 },
        { q: "Để import một package?", a: ["import java.util", "include java.util", "using java.util", "include <java.util>"], c: 0 },
        { q: "String immutable trong Java?", a: ["Không", "Có", "Tùy trường hợp", "Chỉ khi được khởi tạo"], c: 1 },
        { q: "new từ khóa dùng để?", a: ["Tạo biến", "Tạo object", "Import class", "Khai báo hàm"], c: 1 },
        { q: "this trong Java là gì?", a: ["Một từ khóa", "Tham chiếu đến object hiện tại", "Một hằng số", "Một interface"], c: 1 },
        { q: "super trong Java dùng để?", a: ["Tạo class", "Gọi method từ parent class", "Tạo interface", "Khai báo hàm"], c: 1 },
        { q: "static keyword dùng để?", a: ["Tạo biến địa phương", "Tạo thành viên chung cho class", "Tạo object", "Xóa biến"], c: 1 },
        { q: "final keyword dùng để?", a: ["Kết thúc code", "Làm hằng số", "Tạo instance", "Xóa class"], c: 1 },
        { q: "abstract class dùng để?", a: ["Tạo class bình thường", "Tạo class không thể instantiate", "Tạo interface", "Tạo package"], c: 1 },
        { q: "interface trong Java là gì?", a: ["Một class", "Một giao cực để các class implement", "Một biến", "Một method"], c: 1 },
        { q: "try-catch dùng để?", a: ["Vòng lặp", "Xử lý exception", "Tạo class", "Khai báo hàm"], c: 1 },
        { q: "finally block làm gì?", a: ["Chạy khi có lỗi", "Chạy sau try-catch dù có lỗi hay không", "Kết thúc chương trình", "Tạo biến"], c: 1 },
        { q: "throw dùng để?", a: ["Ném ra exception", "Bắt exception", "Tạo exception", "Kiểm tra exception"], c: 0 },
        { q: "Hàm length() trong String trả về?", a: ["Mảy ký tự", "Độ dài string", "Ký tự đầu", "Index"], c: 1 },
        { q: "Hàm substring() dùng để?", a: ["Tạo string mới", "Trích xuất phần của string", "Xóa phần của string", "Nối string"], c: 1 },
        { q: "Hàm indexOf() trả về gì?", a: ["Index của substring đầu tiên", "Số lần xuất hiện", "String con", "Boolean"], c: 0 },
        { q: "Hàm toLowerCase() dùng để?", a: ["Chuyển thành chữ hoa", "Chuyển thành chữ thường", "Xóa ký tự", "Tìm ký tự"], c: 1 },
        { q: "Hàm toUpperCase() dùng để?", a: ["Chuyển thành chữ thường", "Chuyển thành chữ hoa", "Xóa ký tự", "Tìm ký tự"], c: 1 },
        { q: "Hàm trim() dùng để?", a: ["Cắt string", "Loại bỏ khoảng trắng ở hai đầu", "Nối string", "Tìm string"], c: 1 },
        { q: "Hàm replace() dùng để?", a: ["Tìm kiếm", "Thay thế ký tự/string", "Xóa ký tự", "Nối string"], c: 1 },
        { q: "Hàm split() trả về gì?", a: ["Một string", "Một array", "Một list", "Một int"], c: 1 },
        { q: "Hàm equals() so sánh gì?", a: ["Địa chỉ object", "Nội dung string", "Độ dài", "Kiểu dữ liệu"], c: 1 },
        { q: "Hàm equalsIgnoreCase() làm gì?", a: ["So sánh có phân biệt hoa thường", "So sánh không phân biệt hoa thường", "So sánh độ dài", "So sánh địa chỉ"], c: 1 },
        { q: "Hàm compareTo() trả về gì?", a: ["Boolean", "Số âm, 0, hoặc dương", "String", "Void"], c: 1 },
        { q: "Hàm contains() kiểm tra gì?", a: ["Ngoại lệ", "Sự tồn tại của substring", "Độ dài", "Kiểu dữ liệu"], c: 1 },
        { q: "Hàm startsWith() kiểm tra gì?", a: ["String kết thúc bằng gì", "String bắt đầu bằng gì", "Độ dài string", "Ký tự đặc biệt"], c: 1 },
        { q: "Hàm endsWith() kiểm tra gì?", a: ["String bắt đầu bằng gì", "String kết thúc bằng gì", "Độ dài string", "Ký tự đầu"], c: 1 },
        { q: "Hàm add() trong ArrayList dùng để?", a: ["Xóa phần tử", "Thêm phần tử", "Tìm phần tử", "Sắp xếp phần tử"], c: 1 },
        { q: "Hàm remove() trong ArrayList dùng để?", a: ["Thêm phần tử", "Xóa phần tử", "Tìm phần tử", "Sắp xếp phần tử"], c: 1 },
        { q: "Hàm get() trong ArrayList trả về?", a: ["Phần tử tại vị trí", "Tất cả phần tử", "Số lượng phần tử", "Index"], c: 0 },
        { q: "Hàm size() trong ArrayList trả về?", a: ["Phần tử", "Kích thước (số phần tử)", "Index", "Object"], c: 1 },
        { q: "Hàm clear() trong ArrayList dùng để?", a: ["Xóa một phần tử", "Xóa tất cả phần tử", "Lấy phần tử", "Sắp xếp"], c: 1 },
        { q: "Hàm sort() dùng để?", a: ["Tìm phần tử", "Sắp xếp danh sách", "Xóa phần tử", "Nối danh sách"], c: 1 },
        { q: "Hàm Collections.reverse() dùng để?", a: ["Sắp xếp", "Đảo ngược thứ tự", "Tìm phần tử", "Xóa phần tử"], c: 1 },
        { q: "HashMap dùng để?", a: ["Danh sách thứ tự", "Cặp kóa-giá trị", "Tập hợp", "Hàng đợi"], c: 1 },
        { q: "Hàm put() trong HashMap dùng để?", a: ["Lấy giá trị", "Thêm cặp kóa-giá trị", "Xóa cặp", "Tìm kóa"], c: 1 },
        { q: "Hàm get() trong HashMap trả về?", a: ["Kóa", "Giá trị tương ứng với kóa", "Tất cả giá trị", "Index"], c: 1 },
        { q: "Hàm parseInt() dùng để?", a: ["String sang Integer object", "String sang int", "Int sang String", "Kiểm tra int"], c: 1 }
    ],
    csharp: [
        { q: "Hàm in dữ liệu trong C#?", a: ["print()", "cout", "Console.WriteLine()", "printf()"], c: 2 },
        { q: "Khai báo biến C#?", a: ["int age = 25", "age: int = 25", "var age = 25", "Cả A và C"], c: 3 },
        { q: "Array trong C#?", a: ["int[] arr = [1,2,3]", "int arr[] = new int[3]", "array arr = {1,2,3}", "List<int> arr = {1,2,3}"], c: 1 },
        { q: "For loop trong C#?", a: ["for i in range(10)", "for(int i=0; i<10; i++)", "for(i<10)", "repeat 10"], c: 1 },
        { q: "List trong C# là gì?", a: ["Array cố định", "Array động", "Hàm", "Namespace"], c: 1 },
        { q: "Namespace dùng để?", a: ["Import class", "Nhóm code", "Khai báo hàm", "Tạo biến"], c: 1 },
        { q: "Property trong C#?", a: ["Biến public", "Biến với getter/setter", "Hàm", "Constant"], c: 1 },
        { q: "async/await là gì?", a: ["Vòng lặp", "Lập trình không đồng bộ", "Khai báo hàm", "Điều kiện"], c: 1 },
        { q: "LINQ là gì?", a: ["Namespace", "Phương pháp truy vấn dữ liệu", "Type dữ liệu", "Hàm"], c: 1 },
        { q: "Nullable type trong C#?", a: ["Biến có thể null", "Biến không thể null", "Biến kiểu Integer", "Biến tĩnh"], c: 0 },
        { q: "this trong C# là gì?", a: ["Một từ khóa", "Tham chiếu đến object hiện tại", "Một hằng số", "Một method"], c: 1 },
        { q: "base trong C# dùng để?", a: ["Tạo class", "Gọi method từ parent class", "Tạo interface", "Khai báo hàm"], c: 1 },
        { q: "static dùng để?", a: ["Tạo biến địa phương", "Tạo thành viên chung cho class", "Tạo object", "Xóa biến"], c: 1 },
        { q: "const dùng để?", a: ["Biến có thể thay đổi", "Hằng số không thể thay đổi", "Biến từ khóa", "Một loại con trỏ"], c: 1 },
        { q: "abstract class dùng để?", a: ["Tạo class bình thường", "Tạo class không thể instantiate", "Tạo interface", "Tạo package"], c: 1 },
        { q: "interface trong C# là gì?", a: ["Một class", "Một giao cực để các class implement", "Một biến", "Một method"], c: 1 },
        { q: "try-catch dùng để?", a: ["Vòng lặp", "Xử lý exception", "Tạo class", "Khai báo hàm"], c: 1 },
        { q: "finally block làm gì?", a: ["Chạy khi có lỗi", "Chạy sau try-catch dù có lỗi hay không", "Kết thúc chương trình", "Tạo biến"], c: 1 },
        { q: "throw dùng để?", a: ["Ném ra exception", "Bắt exception", "Tạo exception", "Kiểm tra exception"], c: 0 },
        { q: "Hàm Length trong String trả về?", a: ["Mảy ký tự", "Độ dài string", "Ký tự đầu", "Index"], c: 1 },
        { q: "Hàm Substring() dùng để?", a: ["Tạo string mới", "Trích xuất phần của string", "Xóa phần của string", "Nối string"], c: 1 },
        { q: "Hàm IndexOf() trả về gì?", a: ["Index của substring đầu tiên", "Số lần xuất hiện", "String con", "Boolean"], c: 0 },
        { q: "Hàm ToLower() dùng để?", a: ["Chuyển thành chữ hoa", "Chuyển thành chữ thường", "Xóa ký tự", "Tìm ký tự"], c: 1 },
        { q: "Hàm ToUpper() dùng để?", a: ["Chuyển thành chữ thường", "Chuyển thành chữ hoa", "Xóa ký tự", "Tìm ký tự"], c: 1 },
        { q: "Hàm Trim() dùng để?", a: ["Cắt string", "Loại bỏ khoảng trắng ở hai đầu", "Nối string", "Tìm string"], c: 1 },
        { q: "Hàm Replace() dùng để?", a: ["Tìm kiếm", "Thay thế ký tự/string", "Xóa ký tự", "Nối string"], c: 1 },
        { q: "Hàm Split() trả về gì?", a: ["Một string", "Một array", "Một list", "Một int"], c: 1 },
        { q: "Hàm Equals() so sánh gì?", a: ["Địa chỉ object", "Nội dung string", "Độ dài", "Kiểu dữ liệu"], c: 1 },
        { q: "Hàm Contains() kiểm tra gì?", a: ["Ngoại lệ", "Sự tồn tại của substring", "Độ dài", "Kiểu dữ liệu"], c: 1 },
        { q: "Hàm StartsWith() kiểm tra gì?", a: ["String kết thúc bằng gì", "String bắt đầu bằng gì", "Độ dài string", "Ký tự đặc biệt"], c: 1 },
        { q: "Hàm EndsWith() kiểm tra gì?", a: ["String bắt đầu bằng gì", "String kết thúc bằng gì", "Độ dài string", "Ký tự đầu"], c: 1 },
        { q: "Hàm Add() trong List dùng để?", a: ["Xóa phần tử", "Thêm phần tử", "Tìm phần tử", "Sắp xếp phần tử"], c: 1 },
        { q: "Hàm Remove() trong List dùng để?", a: ["Thêm phần tử", "Xóa phần tử", "Tìm phần tử", "Sắp xếp phần tử"], c: 1 },
        { q: "Hàm Count trong List trả về?", a: ["Phần tử", "Kích thước (số phần tử)", "Index", "Object"], c: 1 },
        { q: "Hàm Clear() trong List dùng để?", a: ["Xóa một phần tử", "Xóa tất cả phần tử", "Lấy phần tử", "Sắp xếp"], c: 1 },
        { q: "Hàm Sort() dùng để?", a: ["Tìm phần tử", "Sắp xếp danh sách", "Xóa phần tử", "Nối danh sách"], c: 1 },
        { q: "Hàm Reverse() dùng để?", a: ["Sắp xếp", "Đảo ngược thứ tự", "Tìm phần tử", "Xóa phần tử"], c: 1 },
        { q: "Dictionary trong C# dùng để?", a: ["Danh sách thứ tự", "Cặp kóa-giá trị", "Tập hợp", "Hàng đợi"], c: 1 },
        { q: "Hàm Add() trong Dictionary dùng để?", a: ["Lấy giá trị", "Thêm cặp kóa-giá trị", "Xóa cặp", "Tìm kóa"], c: 1 },
        { q: "property getter/setter là gì?", a: ["Hàm thường", "Cách kiểm soát truy cập thuộc tính", "Một biến", "Một constant"], c: 1 },
        { q: "delegate trong C# là gì?", a: ["Một biến", "Một thành viên của class", "Một kiểu tham chiếu đến hàm", "Một interface"], c: 2 },
        { q: "event trong C# là gì?", a: ["Một hàm", "Cơ chế phát thông báo", "Một biến", "Một method"], c: 1 },
        { q: "using statement dùng để?", a: ["Import namespace", "Quản lý tài nguyên tự động", "Tạo biến", "Khai báo hàm"], c: 1 }
    ]
};
